---
- name: Create VM
  hosts: all  # [inventory group ]
  connection: local
  gather_facts: false



  tasks:
    - name: get the current time for a timestamp
      command: date +%Y%m%d-%H%M%S
      register: time
    
    - name: setting set validate_certs=False
      set: validate_certs=False

#    - name: Including pysphre module
#      command: /usr/lib/python2.6/site-packages/pysphere-0.1.7-py2.6.egg
      
    - name: New Vmware guest vm
       vsphere_guest:
         vcenter_hostname: 192.168.0.240
#        username: #Vcenter user
#        password: #Vcenter Pass
        guest: "{{inventory_hostname_short}}"
        state: powered_on
#        vm_extra_config:
#          vcpu.hotadd: yes
#          mem.hotadd: yes
#          notes: "{{inventory_hostname_short}}"
#        vm_disk:
#          disk1:
#            size_gb: 20
#            type: thin
#            datastore: mydatastore # name of the datastore i will create the vms
#        vm_nic:
#          nic1:
#            type: vmxnet3
#            network: #mynetwork
#            network_type: standard
#        vm_hardware:
#          memory_mb: 2048
#          num_cpus: 2
#          osid: centos64Guest
#          scsi: paravirtual
#        vm_hw_version: vmx-09
#        esxi:
#          datacenter: my-datacenter-name
#          hostname: #any ESXi ip address
#  - name: Start VM creation and OS install
#      debug: var=time.end

#  - name: Fire Up new VM 17 min delay
#      local_action: wait_for host="{{ansible_ssh_host | default(inventory_hostname) }}" port=22 delay=900 timeout=1200
